dist: bionic
language: node_js
node_js:
  - 12.16.1
cache: yarn
git:
  depth: false
branches:
  only:
    - develop
    - "/^feature\\/.*$/"
    - "/^release\\/.*$/"
    - "/^epic\\/.*$/"
defaults: &defaults
  script: './ci-scripts/e2e-cypress.sh'
jobs:
  include:
    - stage: Tests
      env:
        - STAGE_NAME="1x-electron on Travis CI"
      script: './build.sh sonar'
    - stage: Tests
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: Tests
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: Tests
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: Tests
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
notifications:
  email:
    on_failure: always
    on_success: change
addons:
  chrome: stable
  sonarcloud:
    organization: sap
