dist: bionic
language: node_js
node_js:
  - 12.16.1
cache: yarn
git:
  depth: false
branches:
  only:
    - develop
    - "/^feature\\/.*$/"
    - "/^release\\/.*$/"
    - "/^epic\\/.*$/"
defaults: &defaults
  script: "./ci-scripts/e2e-cypress.sh"

- script:
  name: "Cypress smoke tests 1st thread"
  env: STAGE_NAME=4x-electron"
  <<: *defaults
- script:
  name: "Cypress smoke tests 2st thread"
  env: STAGE_NAME=4x-electron"
  <<: *defaults
- script:
  name: "Cypress smoke tests 2st thread"
  env: STAGE_NAME=4x-electron"
  <<: *defaults
- script:
  name: "Cypress smoke tests 2st thread"
  env: STAGE_NAME=4x-electron"
  <<: *defaults

addons:
  chrome: stable
