dist: bionic
language: node_js
node_js:
  - 12.16.1
cache: yarn
git:
  depth: false
branches:
  only:
    - develop
    - master
    - "/^feature\\/.*$/"
    - "/^hotfix\\/.*$/"
    - "/^release\\/.*$/"
    - "/^doc\\/.*$/"
    - "/^epic\\/.*$/"
jobs:
  include:
    - stage: Tests
      script: './build.sh sonar'
    - script: './ci-scripts/e2e-cypress.sh'
notifications:
  email:
    on_failure: always
    on_success: change
addons:
  chrome: stable
  sonarcloud:
    organization: sap
