name: Deployment

on: [push]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Build
        run: yarn && yarn build:core:lib && yarn build -c=ccv2 && node ./deployment/generate-vercel-project.js
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      - name: vercel-url
        uses: marlass/now-deployment@master
        with:
          zeit-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          now-args: 'dist/storefrontapp --local-config ./deployment/now.csr.json'
