on: push
name: Spartacus github actions
jobs:
  e2eTests:
    name: Cypress e2e tests
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.6.0-chrome77
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build:core:lib
          start: start:ci:2005
          working-directory: projects/storefrontapp-e2e-cypress
          command: yarn e2e:cy:run:smoke:ci:2005
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
