on: push
name: Spartacus github actions
jobs:
  e2eTests:
    name: Cypress e2e tests
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.6.0-chrome77
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install root dependencies
        uses: bahmutov/npm-install@v1
      - name: Build Spartacus
        run: yarn build:core:lib
      - name: Start server in the background
        run: yarn start:ci:2005 &
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: projects/storefrontapp-e2e-tests
          command: yarn cy:run:smoke:ci:2005
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
