on: push
name: Spartacus github actions
jobs:
  e2eTests:
    name: Cypress e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: e2e tests
        run: ci-scripts/e2e-cypress.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
