on:
  push:
    branches:
      - develop
      - feature/**
      - release/**
      - epic/**
  pull_request:
    types: [opened, synchronize, reopened]
name: Spartacus github actions
jobs:
  unitTests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@master
      - name: Install root dependencies
        uses: bahmutov/npm-install@v1
      - name: Run unit tests
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./build.sh sonar
